### PR TITLE
Feat: Added the course titles

### PR DESCRIPTION
**Pull request by parmeshwalunj**
- Extracted the Course titles(course names) data from catalog.uta.edu. 
- Updated the csv_to_json.py to add the course titles to the DB.
- Updated the backend and frontend logic to display the course titles.

### CODE REVIEW

**Comment by KevinRouz** [comment]
Hi Parmesh, this is great! I think we are still missing a few course titles. For example, CSE 1325, CSE 2100, KINE 3313, ARCH 3357, etc. These all seem to be on the catalog. Please fix this and it'll be ready to merge!

**Review by kevinrouz — CHANGES_REQUESTED** [review]
Hi Parmesh, this is great! I think we are still missing a few course titles. For example, CSE 1325, CSE 2100, KINE 3313, ARCH 3357, etc. These all seem to be on the catalog. Please fix this and it'll be ready to merge!

**Comment by parmeshwalunj** [comment]
Hey, Kevin! The requested changes have been made. Please review it. Thanks!

**Review by atiqurx — APPROVED** [review]
Looks good. Great work, Parmesh.

**Comment by parmeshwalunj** [comment]
Thank you!!

**Pull request merged**
